const { describe, it, before, after, mock } = require('node:test');
const assert = require('node:assert');
const contentEngine = require('../scripts/content_engine.js');

describe('Content Engine', () => {

    // Helper to mock Gemini client
    const createMockClient = (responseText, shouldThrow = false) => {
        return {
            getGenerativeModel: () => ({
                generateContent: async () => {
                    if (shouldThrow) throw new Error('API Error');
                    return {
                        response: Promise.resolve({
                            text: () => responseText
                        })
                    };
                }
            })
        };
    };

    it('should fall back to mock implementation when no API key/client is set', async () => {
        // Ensure no client is set
        contentEngine.setGenAI(null);

        const persona = { type: 'shitposter' };
        const topic = 'Coffee';

        const text = await contentEngine.generatePostText(persona, topic);

        assert.ok(typeof text === 'string');
        assert.ok(text.length > 0);

        // Verify mock behavior for shitposter (lowercase and no dots)
        // Since we know the mock logic:
        // if (persona.type === 'shitposter') text = text.toLowerCase().replace('.', '');
        // The mock variations all have punctuation or mixed case.
        // e.g. "Just thinking about ${topic}... 🤔" -> "just thinking about coffee... 🤔" (no dot replacement if it's '...')
        // Wait, replace('.', '') only replaces the first dot.
        // But let's check basic properties.
        assert.strictEqual(text, text.toLowerCase());
    });

    it('should use Gemini API when client is set', async () => {
        const expectedResponse = 'Generated by AI for Coffee';
        const mockClient = createMockClient(expectedResponse);
        contentEngine.setGenAI(mockClient);

        const persona = { type: 'visionary' };
        const topic = 'Coffee';

        const text = await contentEngine.generatePostText(persona, topic);

        assert.strictEqual(text, expectedResponse);
    });

    it('should fall back to mock when API throws error', async () => {
        const mockClient = createMockClient('', true); // Throws error
        contentEngine.setGenAI(mockClient);

        const persona = { type: 'policy_analyst' };
        const topic = 'AI Regulation';

        // Capture console.warn to suppress output during test
        const originalWarn = console.warn;
        let warned = false;
        console.warn = (...args) => {
            if (args[0].includes('Gemini API call failed')) warned = true;
        };

        try {
            const text = await contentEngine.generatePostText(persona, topic);

            assert.ok(typeof text === 'string');
            assert.ok(text.length > 0);
            // Verify mock behavior for policy_analyst
            assert.ok(text.startsWith('[ANALYSIS]'));
            assert.ok(warned, 'Should have logged a warning');
        } finally {
            console.warn = originalWarn;
        }
    });

    describe('generateMockPostText', () => {
        const topic = 'Decentralization';

        it('should return policy analysis for policy_analyst persona', () => {
            const persona = { type: 'policy_analyst' };
            const text = contentEngine.generateMockPostText(persona, topic);
            assert.strictEqual(text, `[ANALYSIS] Regarding ${topic}: Critical implications emerging.`);
        });

        it('should lowercase and remove first dot for shitposter persona', () => {
            const persona = { type: 'shitposter' };

            // Test Variation 4: `${topic}. That's it. That's the tweet.`
            let mockRandom = mock.method(Math, 'random', () => 0.6); // 0.6 * 5 = 3
            try {
                const text = contentEngine.generateMockPostText(persona, topic);
                assert.strictEqual(text, "decentralization that's it. that's the tweet.");
            } finally {
                mockRandom.mock.restore();
            }

            // Test Variation 1: `Just thinking about ${topic}... 🤔`
            mockRandom = mock.method(Math, 'random', () => 0.1); // 0.1 * 5 = 0
            try {
                const text = contentEngine.generateMockPostText(persona, topic);
                // "Just thinking about Decentralization... 🤔"
                // -> lowercase: "just thinking about decentralization... 🤔"
                // -> replace('.', ''): "just thinking about decentralization.. 🤔"
                assert.strictEqual(text, "just thinking about decentralization.. 🤔");
            } finally {
                mockRandom.mock.restore();
            }
        });

        it('should return one of the variations for other personas', () => {
            const persona = { type: 'lurker' };
            const text = contentEngine.generateMockPostText(persona, topic);

            const expectedVariations = [
                `Just thinking about ${topic}... 🤔`,
                `Unpopular opinion: ${topic} is overrated. Don't @ me.`,
                `BREAKING: ${topic} just changed everything. 🧵👇`,
                `${topic}. That's it. That's the tweet.`,
                `Why is nobody talking about ${topic}?`
            ];

            assert.ok(expectedVariations.includes(text));
        });

        it('should inject the topic correctly into variations', () => {
            const persona = { type: 'regular' };
            const customTopic = 'Climate Change';

            const mockRandom = mock.method(Math, 'random', () => 0.1); // Picks first variation

            try {
                const text = contentEngine.generateMockPostText(persona, customTopic);
                assert.strictEqual(text, `Just thinking about ${customTopic}... 🤔`);
            } finally {
                mockRandom.mock.restore();
            }
        });
    });
});
