const { describe, it, before, after } = require('node:test');
const assert = require('node:assert');
const contentEngine = require('../scripts/content_engine.js');

describe('Content Engine (Vertex AI)', () => {

    // Helper to mock Vertex AI GenerativeModel
    const createMockModel = (responseText, shouldThrow = false) => {
        return {
            generateContent: async () => {
                if (shouldThrow) throw new Error('Vertex API Error');
                return {
                    response: {
                        candidates: [
                            {
                                content: {
                                    parts: [
                                        { text: responseText }
                                    ]
                                }
                            }
                        ]
                    }
                };
            }
        };
    };

    it('should fall back to mock implementation when no model/project is set', async () => {
        // Ensure no model is set
        contentEngine.setGenerativeModel(null);

        const persona = { type: 'shitposter' };
        const topic = 'Coffee';

        const text = await contentEngine.generatePostText(persona, topic);

        assert.ok(typeof text === 'string');
        assert.ok(text.length > 0);

        // Verify mock behavior
        assert.strictEqual(text, text.toLowerCase());
    });

    it('should use Vertex AI when model is set', async () => {
        const expectedResponse = 'Generated by Vertex AI for Coffee';
        const mockModel = createMockModel(expectedResponse);
        contentEngine.setGenerativeModel(mockModel);

        const persona = { type: 'visionary' };
        const topic = 'Coffee';

        const text = await contentEngine.generatePostText(persona, topic);

        assert.strictEqual(text, expectedResponse);
    });

    it('should fall back to mock when API throws error', async () => {
        const mockModel = createMockModel('', true); // Throws error
        contentEngine.setGenerativeModel(mockModel);

        const persona = { type: 'policy_analyst' };
        const topic = 'AI Regulation';

        // Capture console.warn to suppress output during test
        const originalWarn = console.warn;
        let warned = false;
        console.warn = (...args) => {
            if (args[0] && args[0].includes('Vertex AI call failed')) warned = true;
        };

        try {
            const text = await contentEngine.generatePostText(persona, topic);

            assert.ok(typeof text === 'string');
            assert.ok(text.length > 0);
            // Verify mock behavior for policy_analyst
            assert.ok(text.startsWith('[ANALYSIS]'));
            assert.ok(warned, 'Should have logged a warning');
        } finally {
            console.warn = originalWarn;
        }
    });
});
