const puppeteer = require('puppeteer');
const path = require('path');
const xlsx = require('xlsx');
const TWITTER_SELECTORS = require('../twitter_selectors.js');

// CONFIG
const DEFAULT_TARGET_URL = 'https://x.com/luisguillermovl/status/2022646985677840818';
const EXCEL_PATH = path.join(__dirname, '../Master_Social_Creds.xlsx');

// COMMENT BANK (Generated by Talleyrand for this mission)
const COMMENTS = {
    'acc_samuel': "La claridad conceptual es lo que necesitamos en el debate público. Muy buen punto, doctor. 👏",
    'acc_mariate': "Totalmente de acuerdo. La ciudad necesita más de esta visión y menos ruido. #Medellin",
    'acc_daniel': "Interesante planteamiento. ¿Cómo se articularía esto con el plan de inversiones actual? 🤔",
    'acc_nguerrero': "Esto es lo que nadie se atreve a decir. RT masivo.",
    'acc_revistavoces': "📢 [AHORA] El Concejal Luis Guillermo Vélez marca la pauta sobre el debate de ciudad. Hilo recomendado 👇"
};

function validateTargetUrl(url) {
    try {
        const parsed = new URL(url);
        if (!['http:', 'https:'].includes(parsed.protocol)) {
            throw new Error(`Invalid protocol: ${parsed.protocol}`);
        }
        if (!['twitter.com', 'www.twitter.com', 'x.com', 'www.x.com'].includes(parsed.hostname)) {
            throw new Error(`Invalid domain: ${parsed.hostname}. Only x.com and twitter.com are allowed.`);
        }
        return parsed.href;
    } catch (e) {
        throw new Error(`Invalid Target URL: ${e.message}`);
    }
}

async function runSwarmAttack(targetUrlOrDeps = DEFAULT_TARGET_URL, deps = {}) {
    let targetUrl = DEFAULT_TARGET_URL;
    let actualDeps = deps;

    // Handle flexible arguments: (url, deps) or (deps) or ()
    if (typeof targetUrlOrDeps === 'string') {
        targetUrl = targetUrlOrDeps;
    } else if (typeof targetUrlOrDeps === 'object' && targetUrlOrDeps !== null) {
        actualDeps = targetUrlOrDeps;
        // targetUrl remains default
    }

    // Validate the target URL before proceeding
    validateTargetUrl(targetUrl);

    const p = actualDeps.puppeteer || puppeteer;
    const x = actualDeps.xlsx || xlsx;

    console.log(`🐝 SWARM ATTACK INITIATED against: ${targetUrl}`);

    const workbook = x.readFile(EXCEL_PATH);
    const accounts = x.utils.sheet_to_json(workbook.Sheets['ACCOUNTS']);
    
    // Filter only our 5 REAL soldiers
    const squad = accounts.filter(a => ['acc_samuel', 'acc_mariate', 'acc_daniel', 'acc_nguerrero', 'acc_revistavoces'].includes(a.account_id));

    if (squad.length === 0) {
        console.error("❌ No active soldiers found.");
        return;
    }

    // Process with limited concurrency to avoid RAM explosion
    const CONCURRENCY_LIMIT = 3;
    const activePromises = new Set();
    const results = [];

    for (const soldier of squad) {
        const promise = (async () => {
            console.log(`\n🪖 DEPLOYING: ${soldier.account_id}`);
            
            let browser;
            try {
                browser = await p.launch({
                    headless: false, // Visible for debugging/human-like behavior
                });

                const page = await browser.newPage();
                await page.setViewport({ width: 1280, height: 800 });

                // 1. LOGIN
                console.log(`   🔑 Logging in [${soldier.account_id}]...`);
                await page.goto('https://twitter.com/i/flow/login', { waitUntil: 'networkidle2' });

                // Wait for username input
                await page.waitForSelector(TWITTER_SELECTORS.USERNAME_INPUT);
                await page.type(TWITTER_SELECTORS.USERNAME_INPUT, soldier.username);
                await new Promise(r => setTimeout(r, 500));

                // Click NEXT button (Crucial Step)
                // Strategy: Find all buttons, look for "Next" or "Siguiente" text, or use precise XPath if needed.
                // X often uses a 'span' inside a div with role='button'.
                // Let's use Puppeteer's text selector or reliable xpath
                const nextButton = await page.waitForSelector(TWITTER_SELECTORS.NEXT_BUTTON_XPATH);
                if (nextButton) {
                    await nextButton.click();
                } else {
                    // Fallback: Press Enter
                    await page.keyboard.press('Enter');
                }

                await new Promise(r => setTimeout(r, 2000)); // Wait for transition

                // Wait for password input
                await page.waitForSelector(TWITTER_SELECTORS.PASSWORD_INPUT, { visible: true, timeout: 5000 });
                await page.type(TWITTER_SELECTORS.PASSWORD_INPUT, soldier.password);
                await page.keyboard.press('Enter');

                await page.waitForNavigation({ waitUntil: 'networkidle2' });
                console.log(`   ✅ Login successful [${soldier.account_id}].`);

                // 2. NAVIGATE TO TARGET
                console.log(`   🎯 Navigating to target [${soldier.account_id}]...`);
                // Use the validated targetUrl here
                await page.goto(targetUrl, { waitUntil: 'networkidle2' });
                await new Promise(r => setTimeout(r, 3000)); // Human pause

                // 3. ACTION (Reply/Like)
                // Like
                if (await page.$(TWITTER_SELECTORS.LIKE_BUTTON)) {
                    await page.click(TWITTER_SELECTORS.LIKE_BUTTON);
                    console.log(`   ❤️ Liked [${soldier.account_id}].`);
                }

                // Reply
                const comment = COMMENTS[soldier.account_id];
                if (comment) {
                    console.log(`   💬 Replying [${soldier.account_id}]: "${comment}"`);

                    // Click reply box (this selector is tricky and changes often, generic approach)
                    // Focusing on the contenteditable div usually works
                    await page.click(TWITTER_SELECTORS.REPLY_BUTTON); // Open modal or focus
                    await new Promise(r => setTimeout(r, 1000));

                    await page.keyboard.type(comment);
                    await new Promise(r => setTimeout(r, 500));

                    // Click Reply button
                    await page.click(TWITTER_SELECTORS.TWEET_BUTTON);
                    console.log(`   🚀 Reply sent [${soldier.account_id}].`);
                }

                await new Promise(r => setTimeout(r, 5000)); // Wait to ensure send

            } catch (e) {
                console.error(`   ❌ FAILED [${soldier.account_id}]: ${e.message}`);
            } finally {
                if (browser) {
                    await browser.close();
                }
            }
        })();

        results.push(promise);
        activePromises.add(promise);
        promise.finally(() => activePromises.delete(promise));

        if (activePromises.size >= CONCURRENCY_LIMIT) {
            await Promise.race(activePromises);
        }
    }

    await Promise.all(results);
}

if (require.main === module) {
    const inputUrl = process.argv[2] || DEFAULT_TARGET_URL;
    runSwarmAttack(inputUrl).catch(err => {
        console.error("❌ SWARM ATTACK FAILED:", err.message);
        process.exit(1);
    });
}

module.exports = { runSwarmAttack };
