const puppeteer = require('puppeteer');
const path = require('path');
const xlsx = require('xlsx');

// CONFIG
const TARGET_URL = process.argv[2] || 'https://x.com/luisguillermovl/status/2022646985677840818';
const EXCEL_PATH = path.join(__dirname, '../Master_Social_Creds.xlsx');

// COMMENT BANK (Generated by Talleyrand for this mission)
const COMMENTS = {
    'acc_samuel': "La claridad conceptual es lo que necesitamos en el debate público. Muy buen punto, doctor. 👏",
    'acc_mariate': "Totalmente de acuerdo. La ciudad necesita más de esta visión y menos ruido. #Medellin",
    'acc_daniel': "Interesante planteamiento. ¿Cómo se articularía esto con el plan de inversiones actual? 🤔",
    'acc_nguerrero': "Esto es lo que nadie se atreve a decir. RT masivo.",
    'acc_revistavoces': "📢 [AHORA] El Concejal Luis Guillermo Vélez marca la pauta sobre el debate de ciudad. Hilo recomendado 👇"
};

async function runSwarmAttack(deps = {}) {
    const p = deps.puppeteer || puppeteer;
    const x = deps.xlsx || xlsx;

    console.log(`🐝 SWARM ATTACK INITIATED against: ${TARGET_URL}`);

    const workbook = x.readFile(EXCEL_PATH);
    const accounts = x.utils.sheet_to_json(workbook.Sheets['ACCOUNTS']);
    
    // Filter only our 5 REAL soldiers
    const squad = accounts.filter(a => ['acc_samuel', 'acc_mariate', 'acc_daniel', 'acc_nguerrero', 'acc_revistavoces'].includes(a.account_id));

    if (squad.length === 0) {
        console.error("❌ No active soldiers found.");
        return;
    }

    // Process sequentially to avoid RAM explosion
    for (const soldier of squad) {
        console.log(`\n🪖 DEPLOYING: ${soldier.username} (${soldier.account_id})`);
        
        let browser;
        try {
            browser = await p.launch({
                headless: false, // Visible for debugging/human-like behavior
                args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            
            const page = await browser.newPage();
            await page.setViewport({ width: 1280, height: 800 });

            // 1. LOGIN
            console.log("   🔑 Logging in...");
            await page.goto('https://twitter.com/i/flow/login', { waitUntil: 'networkidle2' });
            
            // Wait for username input
            const userInputSelector = 'input[autocomplete="username"]';
            await page.waitForSelector(userInputSelector);
            await page.type(userInputSelector, soldier.username);
            await new Promise(r => setTimeout(r, 500)); 
            
            // Click NEXT button (Crucial Step)
            // Strategy: Find all buttons, look for "Next" or "Siguiente" text, or use precise XPath if needed.
            // X often uses a 'span' inside a div with role='button'.
            // Let's use Puppeteer's text selector or reliable xpath
            const nextButton = await page.waitForSelector('xpath/.//span[contains(text(), "Siguiente") or contains(text(), "Next")]');
            if (nextButton) {
                await nextButton.click();
            } else {
                // Fallback: Press Enter
                await page.keyboard.press('Enter');
            }
            
            await new Promise(r => setTimeout(r, 2000)); // Wait for transition

            // Wait for password input
            await page.waitForSelector('input[name="password"]', { visible: true, timeout: 5000 });
            await page.type('input[name="password"]', soldier.password);
            await page.keyboard.press('Enter');
            
            await page.waitForNavigation({ waitUntil: 'networkidle2' });
            console.log("   ✅ Login successful.");

            // 2. NAVIGATE TO TARGET
            console.log("   🎯 Navigating to target...");
            await page.goto(TARGET_URL, { waitUntil: 'networkidle2' });
            await new Promise(r => setTimeout(r, 3000)); // Human pause

            // 3. ACTION (Reply/Like)
            // Like
            const likeSelector = 'div[data-testid="like"]';
            if (await page.$(likeSelector)) {
                await page.click(likeSelector);
                console.log("   ❤️ Liked.");
            }

            // Reply
            const comment = COMMENTS[soldier.account_id];
            if (comment) {
                console.log(`   💬 Replying: "${comment}"`);
                
                // Click reply box (this selector is tricky and changes often, generic approach)
                // Focusing on the contenteditable div usually works
                await page.click('div[data-testid="reply"]'); // Open modal or focus
                await new Promise(r => setTimeout(r, 1000));
                
                await page.keyboard.type(comment);
                await new Promise(r => setTimeout(r, 500));
                
                // Click Reply button
                await page.click('div[data-testid="tweetButton"]');
                console.log("   🚀 Reply sent.");
            }

            await new Promise(r => setTimeout(r, 5000)); // Wait to ensure send
            // Browser will be closed in finally block

        } catch (e) {
            console.error(`   ❌ FAILED: ${e.message}`);
        } finally {
            if (browser) {
                await browser.close();
            }
        }
    }
}

if (require.main === module) {
    runSwarmAttack();
}

module.exports = { runSwarmAttack };
